### ISSUE TITLE
Build.sh

### ISSUE THREAD

**Issue by Keryen** [pimpale/c-opencl-raymarcher#1]
I have some errors when executing the build.sh

I attach the below:

main.c: In function ‘set_size’:
main.c:214:17: warning: implicit declaration of function ‘reallocarray’; did you mean ‘reallocf’? [-Wimplicit-function-declaration]
   framebuffer = reallocarray(framebuffer, point_count, sizeof(uint32_t));
                 ^~~~~~~~~~~~
                 reallocf
main.c:214:15: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   framebuffer = reallocarray(framebuffer, point_count, sizeof(uint32_t));
               ^
/tmp/ccR6I9ks.o: En la función `quat_rotate':
main.c:(.text+0x362): referencia a `sinf' sin definir
main.c:(.text+0x3c9): referencia a `cosf' sin definir
/tmp/ccR6I9ks.o: En la función `init_cl':
main.c:(.text+0x551): referencia a `clGetDeviceIDs' sin definir
main.c:(.text+0x5a3): referencia a `clGetDeviceIDs' sin definir
main.c:(.text+0x5ca): referencia a `clCreateContext' sin definir
main.c:(.text+0x5f1): referencia a `clCreateCommandQueueWithProperties' sin definir
/tmp/ccR6I9ks.o: En la función `init_x':
main.c:(.text+0x61d): referencia a `XOpenDisplay' sin definir
main.c:(.text+0x68e): referencia a `XCreateSimpleWindow' sin definir
main.c:(.text+0x6b7): referencia a `XSelectInput' sin definir
main.c:(.text+0x6d7): referencia a `XCreateGC' sin definir
main.c:(.text+0x6fc): referencia a `XSetBackground' sin definir
main.c:(.text+0x71a): referencia a `XSetForeground' sin definir
main.c:(.text+0x733): referencia a `XClearWindow' sin definir
main.c:(.text+0x74c): referencia a `XMapRaised' sin definir
/tmp/ccR6I9ks.o: En la función `delete_x':
main.c:(.text+0x76c): referencia a `XFreeGC' sin definir
main.c:(.text+0x785): referencia a `XDestroyWindow' sin definir
main.c:(.text+0x794): referencia a `XCloseDisplay' sin definir
/tmp/ccR6I9ks.o: En la función `update_user_input':
main.c:(.text+0x7fd): referencia a `XNextEvent' sin definir
main.c:(.text+0x903): referencia a `XLookupKeysym' sin definir
main.c:(.text+0xa44): referencia a `XLookupKeysym' sin definir
main.c:(.text+0xbbc): referencia a `XPending' sin definir
/tmp/ccR6I9ks.o: En la función `set_eye':
main.c:(.text+0xc32): referencia a `clSetKernelArg' sin definir
/tmp/ccR6I9ks.o: En la función `set_rotation':
main.c:(.text+0xc6c): referencia a `clSetKernelArg' sin definir
/tmp/ccR6I9ks.o: En la función `set_size':
main.c:(.text+0xce2): referencia a `clReleaseMemObject' sin definir
main.c:(.text+0xd14): referencia a `clCreateBuffer' sin definir
main.c:(.text+0xd3b): referencia a `clSetKernelArg' sin definir
main.c:(.text+0xd5b): referencia a `clSetKernelArg' sin definir
main.c:(.text+0xd7b): referencia a `clSetKernelArg' sin definir
/tmp/ccR6I9ks.o: En la función `initialize':
main.c:(.text+0xeae): referencia a `clCreateProgramWithSource' sin definir
main.c:(.text+0xedb): referencia a `clBuildProgram' sin definir
main.c:(.text+0xf62): referencia a `clGetProgramBuildInfo' sin definir
main.c:(.text+0xf9e): referencia a `clGetProgramBuildInfo' sin definir
main.c:(.text+0xfe2): referencia a `clCreateKernel' sin definir
/tmp/ccR6I9ks.o: En la función `loop':
main.c:(.text+0x15b1): referencia a `clSetKernelArg' sin definir
main.c:(.text+0x1653): referencia a `clEnqueueNDRangeKernel' sin definir
main.c:(.text+0x16ad): referencia a `clEnqueueReadBuffer' sin definir
main.c:(.text+0x16c0): referencia a `clFinish' sin definir
main.c:(.text+0x1722): referencia a `XSetForeground' sin definir
main.c:(.text+0x1762): referencia a `XFillRectangle' sin definir
/tmp/ccR6I9ks.o: En la función `finalize':
main.c:(.text+0x17dd): referencia a `clReleaseMemObject' sin definir
collect2: error: ld returned 1 exit status

**Comment by pimpale** [comment]
Hi,

`reallocarray` is a nonstandard C function, I've now replaced it with the more standard `realloc`, so it shouldn't be a problem anymore. 

As for the other errors, they seem to be linking errors of some sort. Perhaps you don't have the libraries installed, or you're on a different OS? I built this successfully on Linux,  and I'm not sure if it'll work on Windows or Mac OS, as I don't have those computers available to me at the moment.

**Comment by Keryen** [comment]
I have found some more errors.

FIrst, there is a fprintf() with bad sintaxys in main.c: fprintf(stderr, "%s", buffer); instead of fprintf(stderr, buffer);

After the new commit I still get the errors I said before and I have found why. The command inside build.sh should be the following for applying the imported libraries, the order is relevant: 
gcc -std=gnu99 -o clrenderer main.c -lm -lX11 -lOpenCL

**Comment by Keryen** [comment]
Finally, you should also add the extension ".cl" to the OpenCL files, they seem to be text plain, so you can them better like warp.cl and sierpinski.cl

**Comment by pimpale** [comment]
Thanks for catching that. For some reason it was building correctly despite the incorrect order on my computer. Anyway, I've made all the changes that you've suggested. Please let me know if you run into any other problems.
